# Generated by Django 3.2.3 on 2021-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('score', models.IntegerField()),
                ('total_game_play', models.IntegerField()),
            ],
        ),
    ]
